spring:
  application:
    name: service-tenant
  config:
    enabled: true
    import: configserver:https://service-config.azurewebsites.net
  cloud:
    config:
      username: ${EUR_USER}
      password: ${EUR_PASS}
  cors_origin: http://localhost:4200
