spring:
  application:
    name: service-tenant
  config:
    enabled: true
    import: configserver:https://service-config.azurewebsites.net
  cloud:
    config:
      username: ${EUR_USER}
      password: ${EUR_PASS}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://login.microsoftonline.com/3363f614-6ea7-4f25-bc97-aadc48a24082/discovery/v2.0/keys
          issuer-uri: https://login.microsoftonline.com/3363f614-6ea7-4f25-bc97-aadc48a24082/v2.0
logging:
  level:
    org.springframework.security: DEBUG
settings:
  cors_origin: http://localhost:4200
